<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgW1AA9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgW1AA9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNgW1AA9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNgW1AA9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNgW1AA9\App_KernelDevDebugContainer([
    'container.build_hash' => 'NgW1AA9',
    'container.build_id' => 'a04c33e9',
    'container.build_time' => 1757502790,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgW1AA9');
