<?php

namespace ContainerNgW1AA9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0FM3B4hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0FM3B4h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0FM3B4h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'food' => ['privates', '.errored.X5I.noE', NULL, 'Cannot determine controller argument for "App\\Controller\\FoodController::show()": the $food argument is type-hinted with the non-existent class or interface: "App\\Entity\\Food".'],
        ], [
            'food' => '?',
        ]);
    }
}
