<?php

namespace ContainerNgW1AA9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J0TtEGUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J0TtEGU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J0TtEGU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\FoodController::delete' => ['privates', '.service_locator.zoKWsE4', 'get_ServiceLocator_ZoKWsE4Service', true],
            'App\\Controller\\FoodController::edit' => ['privates', '.service_locator.cha9AUK', 'get_ServiceLocator_Cha9AUKService', true],
            'App\\Controller\\FoodController::index' => ['privates', '.service_locator.DrQ64D1', 'get_ServiceLocator_DrQ64D1Service', true],
            'App\\Controller\\FoodController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\FoodController::show' => ['privates', '.service_locator.0FM3B4h', 'get_ServiceLocator_0FM3B4hService', true],
            'App\\Controller\\PlatController::Delete' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\PlatController::edit' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\PlatController::index' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\PlatController::new' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\PlatController::show' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\FoodController:delete' => ['privates', '.service_locator.zoKWsE4', 'get_ServiceLocator_ZoKWsE4Service', true],
            'App\\Controller\\FoodController:edit' => ['privates', '.service_locator.cha9AUK', 'get_ServiceLocator_Cha9AUKService', true],
            'App\\Controller\\FoodController:index' => ['privates', '.service_locator.DrQ64D1', 'get_ServiceLocator_DrQ64D1Service', true],
            'App\\Controller\\FoodController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\FoodController:show' => ['privates', '.service_locator.0FM3B4h', 'get_ServiceLocator_0FM3B4hService', true],
            'App\\Controller\\PlatController:Delete' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\PlatController:edit' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\PlatController:index' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\PlatController:new' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\PlatController:show' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\FoodController::delete' => '?',
            'App\\Controller\\FoodController::edit' => '?',
            'App\\Controller\\FoodController::index' => '?',
            'App\\Controller\\FoodController::new' => '?',
            'App\\Controller\\FoodController::show' => '?',
            'App\\Controller\\PlatController::Delete' => '?',
            'App\\Controller\\PlatController::edit' => '?',
            'App\\Controller\\PlatController::index' => '?',
            'App\\Controller\\PlatController::new' => '?',
            'App\\Controller\\PlatController::show' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FoodController:delete' => '?',
            'App\\Controller\\FoodController:edit' => '?',
            'App\\Controller\\FoodController:index' => '?',
            'App\\Controller\\FoodController:new' => '?',
            'App\\Controller\\FoodController:show' => '?',
            'App\\Controller\\PlatController:Delete' => '?',
            'App\\Controller\\PlatController:edit' => '?',
            'App\\Controller\\PlatController:index' => '?',
            'App\\Controller\\PlatController:new' => '?',
            'App\\Controller\\PlatController:show' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
