<?php

namespace ContainerNgW1AA9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DrQ64D1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DrQ64D1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DrQ64D1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'foodRepository' => ['privates', 'App\\Repository\\FoodRepository', 'getFoodRepositoryService', true],
        ], [
            'foodRepository' => 'App\\Repository\\FoodRepository',
        ]);
    }
}
