<?php

namespace ContainerNgW1AA9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_TfVQyDBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.TfVQyDB' shared service.
     *
     * @return \App\Entity\Food
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\FoodController::edit()": the $food argument is type-hinted with the non-existent class or interface: "App\\Entity\\Food".');
    }
}
