<?php

namespace ContainerNgW1AA9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZoKWsE4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zoKWsE4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zoKWsE4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'food' => ['privates', '.errored.RCshueV', NULL, 'Cannot determine controller argument for "App\\Controller\\FoodController::delete()": the $food argument is type-hinted with the non-existent class or interface: "App\\Entity\\Food".'],
        ], [
            'entityManager' => '?',
            'food' => '?',
        ]);
    }
}
