<?php

namespace ContainerNgW1AA9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BookingController' shared autowired service.
     *
     * @return \App\Controller\BookingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'BookingController.php';

        $container->services['App\\Controller\\BookingController'] = $instance = new \App\Controller\BookingController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\BookingRepository'] ?? $container->load('getBookingRepositoryService')), ($container->privates['serializer'] ?? self::getSerializerService($container)), ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['App\\Repository\\RestaurantRepository'] ?? $container->load('getRestaurantRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\BookingController', $container));

        return $instance;
    }
}
